### ISSUE TITLE
Factorized TDNN models not working 

### ISSUE THREAD

**Issue by cogmeta** [mpuels/docker-py-kaldi-asr-and-model#1]
sudo bash docker-run.bash
Starting cogmeta-py-kaldi_asr-and-model:kaldi-generic-en-tdnn_f-r20180901
INFO:root:model loading model from /opt/kaldi-model ...
Traceback (most recent call last):
  File "cogmeta_asr_local.py", line 211, in <module>
    nnet3_model = KaldiNNet3OnlineModel (kaldi_model_dir, kaldi_model)
  File "kaldiasr/nnet3.pyx", line 134, in kaldiasr.nnet3.KaldiNNet3OnlineModel.__cinit__
RuntimeError

**Comment by cogmeta** [comment]
kaldi-generic-en-tdnn_250-r20180815 model works fine but factorized TDNN model not working. @goofy metions it is resoled here https://github.com/gooofy/zamia-speech/issues/31. 

>  I have pushed libkaldi-asr version 5.4 packages today which should enable you to run and build tdnn_f models.



`
